# Generated by Django 3.0.6 on 2020-08-17 00:33

# Imports from Django
from django.db import migrations, models

# Local Imports
import hikers.models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_unsubscribed_user'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='added_by',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='equipment_recommended',
                to='hikers.Hiker'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='gear_type',
            field=models.CharField(
                choices=[
                    ('clothes',
                     'Apparel'),
                    ('footwear',
                     'Footwear'),
                    ('safety',
                     'Safety/First Aid')],
                max_length=20),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(
                fields=['gear_type'],
                name='gear_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(
                fields=['recommended_gear'],
                name='gear_rec_idx'),
        ),
    ]
