# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hikers', '0001_initial'),
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('gear_type', models.CharField(choices=[(b'clothes', 'Apparel'), (b'footwear', 'Footwear'), (b'safety', 'Safety/First Aid')], max_length=20)),
                ('recommended_gear', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_recommended', to='hikers.Hiker')),
                ('hike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='hikes.Hike')),
            ],
            options={
                'ordering': ['gear_type', '-modified'],
                'verbose_name': 'Equipment',
            },
        ),
    ]
