# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:56
from __future__ import unicode_literals

# Imports from Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hikes', '0001_squashed_0009_auto_20160618_1712'),
        ('hikers', '0001_squashed_0005_auto_20160613_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hazard_type', models.CharField(
                    choices=[('trail', 'Trail Damage'),
                             ('weather', 'Weather Effects'),
                             ('permanent', 'General/On-going Conditions'),
                             ('other', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('date_resolved', models.DateTimeField(blank=True, null=True)),
                ('hike', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='hazards', to='hikes.Hike')),
                ('reported_by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='reported_hazards', to='hikers.Hiker')),
                ('resolution_reported_by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='resolved_hazards', to='hikers.Hiker')),
            ],
            options={
                'ordering': ['-created', '-date_resolved'],
            },
        ),
    ]
