# Generated by Django 3.0.6 on 2020-08-17 00:34

# Imports from Django
from django.db import migrations, models

# Local Imports
import hikers.models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_unsubscribed_user'),
        ('hazards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='date_resolved',
            field=models.DateTimeField(
                null=True),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='hazard_type',
            field=models.CharField(
                choices=[
                    ('trail',
                     'Trail Damage'),
                    ('weather',
                     'Weather Effects'),
                    ('permanent',
                     'General/On-going Conditions'),
                    ('other',
                     'Other')],
                max_length=15),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='reported_by',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='reported_hazards',
                to='hikers.Hiker'),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='resolution_reported_by',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='resolved_hazards',
                to='hikers.Hiker'),
        ),
        migrations.AddIndex(
            model_name='hazard',
            index=models.Index(
                fields=['hazard_type'],
                name='hazard_idx'),
        ),
    ]
