# Generated by Django 3.0.6 on 2020-08-16 23:37

# Imports from Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0003_auto_20200816_2315'),
        ('hikes', '0001_squashed_0009_auto_20160618_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='country_region',
        ),
        migrations.AlterModelOptions(
            name='trailhead',
            options={
                'ordering': [
                    'state_province',
                    'name']},
        ),
        migrations.AddField(
            model_name='trailhead',
            name='state_province',
            field=models.ForeignKey(
                default=44,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='trailheads',
                to='localities.StateProvince'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty_level',
            field=models.CharField(
                choices=[
                    ('0easy',
                     'Easy'),
                    ('1moderate',
                     'Moderate'),
                    ('2difficult',
                     'Difficult')],
                default='0easy',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty_level_explanation',
            field=models.CharField(
                blank=True,
                default='',
                max_length=250),
        ),
        migrations.AlterField(
            model_name='hike',
            name='hike_type',
            field=models.CharField(
                choices=[
                    ('loop',
                     'Loop'),
                    ('out_and_back',
                     'Out and Back'),
                    ('lollipop',
                     'Lollipop/Dog Bone'),
                    ('point_to_point',
                     'Point-to-Point/Destination')],
                default='loop',
                max_length=50),
        ),
        migrations.AlterField(
            model_name='hike',
            name='trail_map',
            field=models.FileField(
                null=True,
                upload_to='trail_maps'),
        ),
        migrations.AlterField(
            model_name='trailhead',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='hike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trailhead',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='hike',
            index=models.Index(
                fields=['hike_type'],
                name='hike_type_idx'),
        ),
        migrations.AddIndex(
            model_name='hike',
            index=models.Index(
                fields=['difficulty_level'],
                name='difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='trailhead',
            index=models.Index(
                fields=['name'],
                name='trailhead_idx'),
        ),
        migrations.AddConstraint(
            model_name='trailhead',
            constraint=models.UniqueConstraint(
                fields=(
                    'state_province',
                    'name'),
                name='unique_trailhead'),
        ),
        migrations.DeleteModel(
            name='CountryRegion',
        ),
        migrations.RemoveField(
            model_name='trailhead',
            name='num_hikes',
        ),
        migrations.RemoveField(
            model_name='trailhead',
            name='region',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
