# Generated by Django 3.0.6 on 2020-08-17 00:11

# Imports from Django
from django.db import migrations

# Local imports
from ..models import unsubscribed_user


def initialize_unsubscribed_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Hiker = apps.get_model('hikers', 'Hiker')
    user, _ = User.objects.get_or_create(username=unsubscribed_user)
    Hiker.objects.get_or_create(hiker=user)


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0002_auto_20200817_0002'),
    ]

    operations = [
        migrations.RunPython(
            initialize_unsubscribed_user, migrations.RunPython.noop
        )
    ]
