# Generated by Django 3.0.6 on 2020-08-17 00:23

# Imports from Django
from django.db import migrations, models

# Local Imports
import hikers.models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_unsubscribed_user'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikephoto',
            name='hiker',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='hike_photos_by_hiker',
                to='hikers.Hiker'),
        ),
        migrations.AlterField(
            model_name='hikephoto',
            name='photo',
            field=models.ImageField(
                upload_to='hike_photos'),
        ),
        migrations.AlterField(
            model_name='hikereview',
            name='hiker',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='reviews_by_hiker',
                to='hikers.Hiker'),
        ),
    ]
