# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-22 13:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# hikes.migrations.0004_auto_20160511_0131

class Migration(migrations.Migration):

    replaces = [(b'hikes', '0001_initial'),
                (b'hikes', '0002_auto_20160421_1417'),
                (b'hikes', '0003_trailhead_point'),
                (b'hikes', '0004_auto_20160511_0131'),
                (b'hikes', '0005_auto_20160617_2249'),
                (b'hikes', '0006_auto_20160618_0224'),
                (b'hikes', '0007_auto_20160618_0226'),
                (b'hikes', '0008_auto_20160618_0239'),
                (b'hikes', '0009_auto_20160618_1712')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('hike_type', models.CharField(
                    choices=[(b'loop', 'Loop'),
                             (b'out_and_back', 'Out and Back'),
                             (b'lollipop', 'Lollipop/Dog Bone'),
                             (b'point_to_point', 'Point-to-Point/Destination')
                             ], default='loop', max_length=50)),
                ('description', models.TextField()),
                ('trail_map', models.FileField(blank=True,
                                               upload_to=b'trail_maps')),
                ('difficulty_level', models.CharField(
                    choices=[(b'0easy', 'Easy'),
                             (b'1moderate', 'Moderate'),
                             (b'2difficult', 'Difficult')],
                    default=b'easy', max_length=20)),
                ('difficulty_level_explanation', models.CharField(
                    blank=True, max_length=250)),
                ('distance', models.FloatField(default=0.0)),
                ('elevation', models.IntegerField(default=0)),
                ('high_point', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['difficulty_level', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_hikes', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trailhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('num_hikes', models.IntegerField(default=1)),
                ('region', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='trailheads', to='hikes.Region')),
                ('slug', models.SlugField(default='slug')),
                ('point', django.contrib.gis.db.models.fields.PointField(
                    default=(0.0, 0.0), srid=4326)),
            ],
            options={
                'ordering': ['region', '-num_hikes'],
            },
        ),
        migrations.AddField(
            model_name='hike',
            name='trailhead',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hikes', to='hikes.Trailhead'),
        ),
        migrations.AddField(
            model_name='hike',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty_level',
            field=models.CharField(
                choices=[(b'0easy', 'Easy'),
                         (b'1moderate', 'Moderate'),
                         (b'2difficult', 'Difficult')],
                default=b'0easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hike',
            unique_together=set([('trailhead', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='trailhead',
            unique_together=set([('region', 'name')]),
        ),
        migrations.RenameField(
            model_name='region',
            old_name='num_hikes',
            new_name='num_trailheads',
        ),
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('country_abbrev', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(
                    blank=True, null=True, srid=4326)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='country_region',
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE,
                related_name='subregions', to='hikes.CountryRegion'),
        ),
    ]
