# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('hike_type', models.CharField(
                    choices=[(b'loop', 'Loop'),
                             (b'out_and_back', 'Out and Back'),
                             (b'lollipop', 'Lollipop/Dog Bone'),
                             (b'point_to_point',
                              'Point-to-Point/Destination')],
                    default='loop', max_length=50)),
                ('description', models.TextField()),
                ('trail_map', models.FileField(blank=True,
                                               upload_to=b'trail_maps')),
                ('difficulty_level', models.CharField(
                    choices=[(b'0easy', 'Easy'), (b'1moderate', 'Moderate'),
                             (b'2difficult', 'Difficult')],
                    default=b'easy', max_length=20)),
                ('difficulty_level_explanation', models.CharField(
                    blank=True, max_length=250)),
                ('distance', models.FloatField(default=0.0)),
                ('elevation', models.IntegerField(default=0)),
                ('high_point', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['difficulty_level', 'distance'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_hikes', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trailhead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('num_hikes', models.IntegerField(default=1)),
                ('region', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='trailheads', to='hikes.Region')),
            ],
            options={
                'ordering': ['region', '-num_hikes'],
            },
        ),
        migrations.AddField(
            model_name='hike',
            name='trailhead',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hikes', to='hikes.Trailhead'),
        ),
    ]
