# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trailhead',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hike',
            name='difficulty_level',
            field=models.CharField(choices=[(b'0easy', 'Easy'),
                                            (b'1moderate', 'Moderate'),
                                            (b'2difficult', 'Difficult')],
                                   default=b'0easy', max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hike',
            unique_together=set([('trailhead', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='trailhead',
            unique_together=set([('region', 'name')]),
        ),
        migrations.RenameField(
            model_name='region',
            old_name='num_hikes',
            new_name='num_trailheads',
        ),
    ]
