# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.contrib.gis.geos import Point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0002_auto_20160421_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailhead',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
