# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 01:31
from __future__ import unicode_literals

from django.contrib.gis.geos import Point
from django.db import migrations


def populate_point(apps, schema_editor):
    Trailhead = apps.get_model("hikes", "Trailhead")  # noqa
    for trailhead in Trailhead.objects.all():
        trailhead.point = Point(trailhead.longitude, trailhead.latitude)
        trailhead.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0003_trailhead_point'),
    ]

    operations = [
        migrations.RunPython(populate_point),
    ]
