# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 22:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0004_auto_20160511_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('country_abbrev', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('geom',
                 django.contrib.gis.db.models.fields.PolygonField(srid=1)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='country_region',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subregions', to='hikes.CountryRegion'),
        ),
    ]
