# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 02:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0007_auto_20160618_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country_region',
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE,
                related_name='subregions', to='hikes.CountryRegion'),
            preserve_default=False,
        ),
    ]
