# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-18 17:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0008_auto_20160618_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryregion',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326),
        ),
    ]
