# Generated by Django 3.0.6 on 2020-08-16 21:22

# Imports from Django
from django.db import migrations

STATES = [
    ('AL', 'Alabama'), ('AK', 'Alaska'),
    ('AS', 'American Samoa'), ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('AA', 'Armed Forces Americas'),
    ('AE', 'Armed Forces Europe'),
    ('AP', 'Armed Forces Pacific'),
    ('CA', 'California'), ('CO', 'Colorado'),
    ('CT', 'Connecticut'), ('DE', 'Delaware'),
    ('DC', 'District of Columbia'),
    ('FL', 'Florida'), ('GA', 'Georgia'),
    ('GU', 'Guam'), ('HI', 'Hawaii'),
    ('ID', 'Idaho'), ('IL', 'Illinois'),
    ('IN', 'Indiana'), ('IA', 'Iowa'),
    ('KS', 'Kansas'), ('KY', 'Kentucky'),
    ('LA', 'Louisiana'), ('ME', 'Maine'),
    ('MD', 'Maryland'), ('MA', 'Massachusetts'),
    ('MI', 'Michigan'), ('MN', 'Minnesota'),
    ('MS', 'Mississippi'), ('MO', 'Missouri'),
    ('MT', 'Montana'), ('NE', 'Nebraska'),
    ('NV', 'Nevada'), ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'), ('NM', 'New Mexico'),
    ('NY', 'New York'), ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('MP', 'Northern Mariana Islands'),
    ('OH', 'Ohio'), ('OK', 'Oklahoma'),
    ('OR', 'Oregon'), ('PA', 'Pennsylvania'),
    ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'), ('TN', 'Tennessee'),
    ('TX', 'Texas'), ('UT', 'Utah'),
    ('VT', 'Vermont'), ('VI', 'Virgin Islands'),
    ('VA', 'Virginia'), ('WA', 'Washington'),
    ('WV', 'West Virginia'), ('WI', 'Wisconsin'),
    ('WY', 'Wyoming')
]


def initial_localities(apps, schema_editor):
    Country = apps.get_model('localities', 'Country')
    StateProvince = apps.get_model('localities', 'StateProvince')

    us, _ = Country.objects.update_or_create(
        alpha_2_code='US', english_short_name='United States'
    )
    for state in STATES:
        code, name = state
        StateProvince.objects.update_or_create(
            country=us, code=code, name=name
        )


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_localities, migrations.RunPython.noop)
    ]
