# Generated by Django 3.0.6 on 2020-08-16 23:15

# Imports from Django
from django.db import migrations

# Local Imports
import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('localities', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateprovince',
            name='code',
            field=core.fields.UpperCaseCharField(max_length=2, unique=True),
        ),
    ]
