# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureHike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hike', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='future_hikes', to='hikes.Hike')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.ImageField(
                    blank=True, upload_to=b'profile_images')),
                ('health_level', models.CharField(
                    choices=[(b'0poor', 'Poor'),
                             (b'1mediocre', 'Mediocre'),
                             (b'2average', 'Average'),
                             (b'3moderate', 'Moderately Fit'),
                             (b'4fit', 'Fit & Active')],
                    default=b'2average', max_length=100)),
                ('avg_walking_pace', models.FloatField(default=2.0)),
                ('miles_walked', models.FloatField(default=0.0)),
                ('hiker', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='hiker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HikerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=50)),
                ('address_line2', models.CharField(blank=True, max_length=50)),
                ('zipcode', localflavor.us.models.USZipCodeField(
                    blank=True, default=b'97219', max_length=10)),
                ('city', models.CharField(default=b'Portland', max_length=50)),
                ('state', localflavor.us.models.USStateField(
                    choices=[(b'AL', 'Alabama'), (b'AK', 'Alaska'),
                             (b'AS', 'American Samoa'), (b'AZ', 'Arizona'),
                             (b'AR', 'Arkansas'),
                             (b'AA', 'Armed Forces Americas'),
                             (b'AE', 'Armed Forces Europe'),
                             (b'AP', 'Armed Forces Pacific'),
                             (b'CA', 'California'), (b'CO', 'Colorado'),
                             (b'CT', 'Connecticut'), (b'DE', 'Delaware'),
                             (b'DC', 'District of Columbia'),
                             (b'FL', 'Florida'), (b'GA', 'Georgia'),
                             (b'GU', 'Guam'), (b'HI', 'Hawaii'),
                             (b'ID', 'Idaho'), (b'IL', 'Illinois'),
                             (b'IN', 'Indiana'), (b'IA', 'Iowa'),
                             (b'KS', 'Kansas'), (b'KY', 'Kentucky'),
                             (b'LA', 'Louisiana'), (b'ME', 'Maine'),
                             (b'MD', 'Maryland'), (b'MA', 'Massachusetts'),
                             (b'MI', 'Michigan'), (b'MN', 'Minnesota'),
                             (b'MS', 'Mississippi'), (b'MO', 'Missouri'),
                             (b'MT', 'Montana'), (b'NE', 'Nebraska'),
                             (b'NV', 'Nevada'), (b'NH', 'New Hampshire'),
                             (b'NJ', 'New Jersey'), (b'NM', 'New Mexico'),
                             (b'NY', 'New York'), (b'NC', 'North Carolina'),
                             (b'ND', 'North Dakota'),
                             (b'MP', 'Northern Mariana Islands'),
                             (b'OH', 'Ohio'), (b'OK', 'Oklahoma'),
                             (b'OR', 'Oregon'), (b'PA', 'Pennsylvania'),
                             (b'PR', 'Puerto Rico'), (b'RI', 'Rhode Island'),
                             (b'SC', 'South Carolina'),
                             (b'SD', 'South Dakota'), (b'TN', 'Tennessee'),
                             (b'TX', 'Texas'), (b'UT', 'Utah'),
                             (b'VT', 'Vermont'), (b'VI', 'Virgin Islands'),
                             (b'VA', 'Virginia'), (b'WA', 'Washington'),
                             (b'WV', 'West Virginia'), (b'WI', 'Wisconsin'),
                             (b'WY', 'Wyoming')],
                    default=b'OR', max_length=2)),
                ('cell_number', localflavor.us.models.PhoneNumberField(
                    blank=True, max_length=20, null=True)),
                ('hiker', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='address', to='hikers.Hiker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HikerPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True,
                                            upload_to=b'hike_photos')),
                ('title', models.CharField(blank=True,
                                           max_length=100, null=True)),
                ('make_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='HikerDiaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, blank=True,
                                           null=True,)),
                ('diary_entry', models.TextField()),
                ('make_public', models.BooleanField(default=False)),
                ('hike', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='diaries_by_hike', to='hikes.Hike')),
                ('hiker', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='diaries', to='hikers.Hiker')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='MyHike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('last_hiked', models.DateField(blank=True, null=True)),
                ('rating', models.CharField(
                    choices=[(b'0never', 'Never Hiked'),
                             (b'1loved', 'Loved It'), (b'2liked', 'Liked It'),
                             (b'3unsure', 'Not Sure'), (b'4ok', 'It Was Ok'), (
                                 b'5had_better', 'Had Better'),
                             (b'6hated', 'Hated It')],
                    default=b'0never', max_length=20)),
                ('hike', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='my_hikes', to='hikes.Hike')),
                ('hiker', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='my_hikes_by_hiker', to='hikers.Hiker')),
            ],
            options={
                'ordering': ['rating'],
            },
        ),
        migrations.AddField(
            model_name='hikerphoto',
            name='diary_entry',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='diary_photos', to='hikers.HikerDiaryEntry'),
        ),
        migrations.AddField(
            model_name='hikerphoto',
            name='hike',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='hiker_photos_by_hike', to='hikes.Hike'),
        ),
        migrations.AddField(
            model_name='hikerphoto',
            name='hiker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='hiker_photos', to='hikers.Hiker'),
        ),
        migrations.AddField(
            model_name='futurehike',
            name='hiker',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='future_hikes_by_hiker', to='hikers.Hiker'),
        ),
        migrations.AlterUniqueTogether(
            name='myhike',
            unique_together=set([('hike', 'hiker')]),
        ),
        migrations.AlterUniqueTogether(
            name='futurehike',
            unique_together=set([('hike', 'hiker')]),
        ),
    ]
