# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiker',
            name='slug',
            field=models.SlugField(default='g', unique=True),
            preserve_default=False,
        ),
    ]
