# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 15:14
from __future__ import unicode_literals

# Imports from Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hikes', '0001_squashed_0009_auto_20160618_1712'),
        ('hikers', '0001_squashed_0005_auto_20160613_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sight_type', models.CharField(
                    choices=[('0view', 'View'),
                             ('1wildlife', 'Wildlife'),
                             ('2flora', 'Plants')], max_length=10)),
                ('description', models.TextField()),
                ('best_time', models.CharField(
                    choices=[('0sunrise', 'Sunrise'),
                             ('1morning', 'Morning'),
                             ('2midday', 'Midday'),
                             ('3evening', 'Early Evening'),
                             ('4sunset', 'Sunset'),
                             ('5dark', 'After Dark')],
                    max_length=10)),
                ('best_season', models.CharField(
                    choices=[('3winter', 'Winter'),
                             ('0spring', 'Spring'),
                             ('1summer', 'Summer'),
                             ('2fall', 'Fall')], max_length=8)),
                ('added_by', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='sights_added', to='hikers.Hiker')),
                ('hike', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sights', to='hikes.Hike')),
            ],
            options={
                'ordering': ['sight_type', 'best_season',
                             'best_time', '-modified'],
            },
        ),
    ]
