# Generated by Django 3.0.6 on 2020-08-17 00:30

# Imports from Django
from django.db import migrations, models

# Local Imports
import hikers.models


class Migration(migrations.Migration):

    dependencies = [
        ('hikers', '0003_unsubscribed_user'),
        ('sights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sight',
            name='added_by',
            field=models.ForeignKey(
                null=True,
                on_delete=hikers.models.SET_UNSUBSCRIBED,
                related_name='sights_added',
                to='hikers.Hiker'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='best_season',
            field=models.CharField(
                choices=[
                    ('3winter',
                     'Winter'),
                    ('0spring',
                     'Spring'),
                    ('1summer',
                     'Summer'),
                    ('2fall',
                     'Fall')],
                max_length=8),
        ),
        migrations.AlterField(
            model_name='sight',
            name='best_time',
            field=models.CharField(
                choices=[
                    ('0sunrise',
                     'Sunrise'),
                    ('1morning',
                     'Morning'),
                    ('2midday',
                     'Midday'),
                    ('3evening',
                     'Early Evening'),
                    ('4sunset',
                     'Sunset'),
                    ('5dark',
                     'After Dark')],
                max_length=10),
        ),
        migrations.AlterField(
            model_name='sight',
            name='sight_type',
            field=models.CharField(
                choices=[
                    ('0view',
                     'View'),
                    ('1wildlife',
                     'Wildlife'),
                    ('2flora',
                     'Plants')],
                max_length=10),
        ),
        migrations.AddIndex(
            model_name='sight',
            index=models.Index(
                fields=['sight_type'],
                name='sight_idx'),
        ),
        migrations.AddIndex(
            model_name='sight',
            index=models.Index(
                fields=['best_season'],
                name='season_idx'),
        ),
        migrations.AddIndex(
            model_name='sight',
            index=models.Index(
                fields=['best_time'],
                name='tod_idx'),
        ),
    ]
